pyms:
  services:
    requests:
      data: ""
    swagger:
      path: "swagger"
      file: "swagger.yaml"
    tracer:
      client: "jaeger"
      host: "jaeger"
      component_name: "Chat BaaS"
  config:
    DEBUG: true
    TESTING: false
    APP_NAME: "Chat BaaS"
    APPLICATION_ROOT : ""
    SECRET_KEY: "gjr39dkjn344_!67#"
    service_host: http://chat-daas:8082/