pyms:
  services:
    swagger:
      path: "swagger"
      file: "swagger.yaml"
    tracer:
      client: "jaeger"
      host: "jaeger"
      component_name: "Chat DaaS"
  config:
    DEBUG: true
    TESTING: false
    APP_NAME: "Chat DaaS"
    SQLALCHEMY_TRACK_MODIFICATIONS: true
    SECRET_KEY: "gjr39dkjn344_!67#"
    SQLALCHEMY_DATABASE_URI: postgres://postgres:postgres@db:5432/chat