pyms:
  services:
    requests:
      data: ""
    tracer:
      client: "jaeger"
      host: "localhost"
      component_name: "Chat Svc"
  config:
    DEBUG: true
    TESTING: true
    APP_NAME: "Chat Svc"
    APPLICATION_ROOT : /
    SECRET_KEY: "gjr39dkjn344_!67#"
    service_host: http://localhost:8083/